### ISSUE TITLE
скорочення запису

### ISSUE THREAD

**Issue by pecourses** [vXIXk/Assignments-repo#23]
https://github.com/vXIXk/Assignments-repo/blob/9eb3dc5ca92e3046ce1772bc9adf9ed4d0166332/js/8index.js#L15-L26
- перша гілка, по суті, зводиться до другої завдяки рекурсії, тому її можна опустити. + можна трохи зменшити вкладеність, з меншою вкладеністю код краще читається:
```javascript
if (exponent === 0) { 
      return 1; 
} 
if (exponent < 0 && exponent >= -100) { 
      return base ** exponent; 
} 
return base * pow(base, --exponent); 
``` 
Ми маємо право не писати `else`, оскільки при виконанні однієї з умов функція заверше свою роботу завдяки `return`, а як умова не вірна, то будемо іти на наступну перевірку.

**Comment by vXIXk** [comment]
Я просто хотіла пригадати світч синтаксис 👍
